2020-05-03 11:15:04,260 INFO: Microblog startup [in C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\__init__.py:46]
2020-05-03 11:15:16,304 ERROR: Exception on /profile [POST] [in C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\orm\base.py", line 379, in _entity_descriptor
    return getattr(entity, key)
AttributeError: type object 'User' has no attribute 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\routes.py", line 235, in profile
    if form.validate_on_submit():
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask_wtf\form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\wtforms\form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\wtforms\form.py", line 152, in validate
    if not field.validate(self, extra):
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\wtforms\fields\core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\wtforms\fields\core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\forms.py", line 230, in validate_password
    user = User.query.filter_by(password=self.password.data).first()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\orm\query.py", line 1642, in filter_by
    for key, value in kwargs.items()]
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\orm\query.py", line 1642, in <listcomp>
    for key, value in kwargs.items()]
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\orm\base.py", line 383, in _entity_descriptor
    (description, key)
sqlalchemy.exc.InvalidRequestError: Entity '<class 'app.models.User'>' has no property 'password'
2020-05-03 11:15:31,848 INFO: Microblog startup [in C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\__init__.py:46]
2020-05-03 11:16:10,984 ERROR: Exception on /profile [POST] [in C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\orm\base.py", line 379, in _entity_descriptor
    return getattr(entity, key)
AttributeError: type object 'User' has no attribute 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\routes.py", line 235, in profile
    if form.validate_on_submit():
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask_wtf\form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\wtforms\form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\wtforms\form.py", line 152, in validate
    if not field.validate(self, extra):
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\wtforms\fields\core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\wtforms\fields\core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\forms.py", line 230, in validate_password
    user = User.query.filter_by(password=self.password.data).first()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\orm\query.py", line 1642, in filter_by
    for key, value in kwargs.items()]
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\orm\query.py", line 1642, in <listcomp>
    for key, value in kwargs.items()]
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\orm\base.py", line 383, in _entity_descriptor
    (description, key)
sqlalchemy.exc.InvalidRequestError: Entity '<class 'app.models.User'>' has no property 'password'
2020-05-03 18:24:23,855 INFO: Microblog startup [in C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\__init__.py:46]
2020-05-03 18:24:33,174 INFO: Microblog startup [in C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\__init__.py:46]
