2020-04-30 21:32:11,811 ERROR: Exception on /register [POST] [in C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\routes.py", line 39, in register
    getinfo=form.getinfo.data)
  File "<string>", line 4, in __init__
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\orm\state.py", line 417, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\orm\state.py", line 414, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 699, in _declarative_constructor
    (k, cls_.__name__))
TypeError: 'password' is an invalid keyword argument for User
2020-04-30 21:32:39,078 ERROR: Exception on /register [POST] [in C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\routes.py", line 39, in register
    getinfo=form.getinfo.data)
  File "<string>", line 4, in __init__
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\orm\state.py", line 417, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\orm\state.py", line 414, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 699, in _declarative_constructor
    (k, cls_.__name__))
TypeError: 'password' is an invalid keyword argument for User
2020-04-30 21:32:39,433 ERROR: Exception on /register [POST] [in C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\routes.py", line 39, in register
    getinfo=form.getinfo.data)
  File "<string>", line 4, in __init__
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\orm\state.py", line 417, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\orm\state.py", line 414, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 699, in _declarative_constructor
    (k, cls_.__name__))
TypeError: 'password' is an invalid keyword argument for User
2020-04-30 21:33:09,811 INFO: Microblog startup [in C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\__init__.py:44]
2020-04-30 21:33:28,920 ERROR: Exception on /register [POST] [in C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\routes.py", line 37, in register
    getinfo=form.getinfo.data)
  File "<string>", line 4, in __init__
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\orm\state.py", line 417, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\orm\state.py", line 414, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 699, in _declarative_constructor
    (k, cls_.__name__))
TypeError: 'password' is an invalid keyword argument for User
2020-04-30 21:36:51,294 INFO: Microblog startup [in C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\__init__.py:44]
2020-04-30 21:39:12,925 INFO: Microblog startup [in C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\__init__.py:44]
2020-04-30 21:39:13,984 ERROR: Exception on /login [GET] [in C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\fungz\ulifestyle_folder\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\routes.py", line 50, in login
    if form.valisdate_on_submit():
AttributeError: 'LoginForm' object has no attribute 'valisdate_on_submit'
2020-04-30 21:40:10,238 INFO: Microblog startup [in C:\Users\fungz\PycharmProjects\Ulifestyle\ulifestyle_folder\app\__init__.py:44]
